import { Client, GatewayIntentBits } from "discord.js";
import { createClient } from "@supabase/supabase-js";
import 'dotenv/config'; // Make sure you install dotenv if running locally

/**
 * ENV VARIABLES
 */
const DISCORD_TOKEN = process.env.DISCORD_TOKEN;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;
const ANNOUNCEMENTS_CHANNEL_ID = "1463920012908695671"; // Your specific inbox channel

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent
  ]
});

client.once("ready", () => {
  console.log(`✅ Airdrop Sailor Bot logged in as ${client.user.tag}`);
});

client.on("messageCreate", async (message) => {
  try {
    // 1. Safety Checks
    if (!message.guild) return; // Ignore DMs
    if (message.channel.id !== ANNOUNCEMENTS_CHANNEL_ID) return; // Ignore other channels
    if (!message.webhookId) return; // "Followed" messages ALWAYS look like webhooks

    // 2. Build Content
    let finalContent = message.content || "";

    // Add Embeds (Followed messages often use embeds)
    if (message.embeds.length > 0) {
      message.embeds.forEach((e) => {
        if (e.title) finalContent += `\n**${e.title}**`;
        if (e.description) finalContent += `\n${e.description}`;
        if (e.url) finalContent += `\n🔗 ${e.url}`;
      });
    }

    // Add Attachments
    if (message.attachments.size > 0) {
      message.attachments.forEach((a) => {
        finalContent += `\n📎 [Attachment](${a.url})`;
      });
    }

    // 3. Deduplication Signature
    // We append the Discord Message ID to ensure we don't process duplicates if the bot restarts
    const signature = `DISCORD_ID:${message.id}`;
    if (finalContent.includes(signature)) return;

    // 4. Determine Project Name
    // CRITICAL FIX: For followed channels, message.author.username is the Project Name (e.g., "Optimism")
    // message.guild.name is YOUR server name.
    const projectName = message.author.username; 
    
    // 5. Insert into Supabase
    const { error } = await supabase
      .from("discord_announcements")
      .insert({
        project_name: projectName, // Saves "Sui", "Optimism", etc.
        channel_name: message.channel.name, // Saves your inbox channel name
        content: finalContent.trim(),
        tag: "announcement"
        // created_at is auto-generated by Supabase
      });

    if (error) {
      console.error("❌ Supabase insert failed:", error.message);
    } else {
      console.log(`📥 Saved update from: ${projectName}`);
    }

  } catch (err) {
    console.error("❌ Unexpected error:", err.message);
  }
});

client.login(DISCORD_TOKEN);
